apps/website/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'

from flask import Flask, render_template

# from flask.ext.bootstrap import Bootstrap
# from flask.ext.mail import Mail
# from flask.ext.moment import Moment
# from flask.ext.sqlalchemy import SQLAlchemy
from config import config_dict
import sys

import logging
from logging.handlers import RotatingFileHandler

# bootstrap = Bootstrap()
# mail = Mail()
# moment = Moment()
# db = SQLAlchemy()
# convert python's encoding to utf8
try:
    from imp import reload

    reload(sys)
    sys.setdefaultencoding('utf8')
except (AttributeError, NameError):
    print "set default coding utf-8 error"


def _import_submodules_from_package(package):
    import pkgutil

    modules = []
    for importer, modname, ispkg in pkgutil.iter_modules(package.__path__, prefix=package.__name__ + "."):
        if ispkg:
            modules.extend(_import_submodules_from_package(__import__(modname, fromlist="dummy")))
        else:
            modules.append(__import__(modname, fromlist="dummy"))
    return modules


def register_routes(app):
    from . import controllers
    from flask.blueprints import Blueprint

    for module in _import_submodules_from_package(controllers):
        if hasattr(module, 'api'):
            bp = getattr(module, 'api')
        else:
            app.logger.error('api not in module')

        if bp and isinstance(bp, Blueprint):
            app.register_blueprint(bp)
        else:
            app.logger.error('bp is not blusprint')

    @app.errorhandler(403)
    def page_403(error):
        app.logger.error("403")
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def error_404(error):
        app.logger.error("404")
        return render_template('errors/404.html'), 404


def create_app(config_mode):
    app = Flask(__name__)
    app.config.from_object(config_dict[config_mode])
    config_dict[config_mode].init_app(app)
    app.config_mode = config_mode

    # 内部日志
    rotating_handler1 = RotatingFileHandler('logs/info.log', maxBytes=1 * 1024 * 1024, backupCount=5)
    rotating_handler2 = RotatingFileHandler('logs/error.log', maxBytes=1 * 1024 * 1024, backupCount=2)
    formatter1 = logging.Formatter("-" * 100 +
                                   '\n %(asctime)s %(levelname)s - '
                                   'in %(funcName)s [%(filename)s:%(lineno)d]:\n %(message)s')
    rotating_handler1.setFormatter(formatter1)
    rotating_handler2.setFormatter(formatter1)
    app.logger.addHandler(rotating_handler1)
    app.logger.addHandler(rotating_handler2)
    app.logger.setLevel(logging.INFO)
    rotating_handler2.setLevel(logging.ERROR)
    if app.config.get("DEBUG"):
        # app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.DEBUG)

    # bootstrap.init_app(app)
    # mail.init_app(app)
    # moment.init_app(app)
    # db.init_app(app)
    register_routes(app)
    # 定时器
    # scheduler.init_app(app)
    # scheduler.start()
    # from apps.routes import main
    # app.register_blueprint(main)

    return app

apps/website/controllers/admin_controller.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'

from flask import Blueprint, current_app, request, jsonify, render_template, url_for, redirect, session

# import json
# from ..mongo import EventDB, ClusterDB, UserDB, QQBindCodeDB, AdminUserDB, ClubDB, AdminDB
# from threading import Thread
# import time, datetime, random
# from ..utils import model2dict, require_value_from_dict, get_value_from_dict
# from ..mredis import RedisClient
# from ..models import Event
from ..services.admin_service import AdminService

api = Blueprint('admin_controller', __name__, url_prefix='/admin')


@api.route('/', methods=['GET'])
def index():
    if AdminService.check_is_need_init():
        return redirect(url_for('init_controller.index'))
    if not AdminService.check_is_login():
        return redirect(url_for('.login'))
    return render_template("admin/main.html")


@api.route('/login', methods=['GET'])
def login():
    return render_template("admin/login.html")


@api.route('/user/list', methods=['GET'])
def user_list():
    users = AdminService.get_user_list()
    return render_template("admin/user/list.html", users=users)


@api.route('/user/add', methods=['GET'])
def user_add():
    return render_template("admin/user/add.html")


@api.route('/user/detail/<user_id>', methods=['GET'])
def user_detail(user_id):
    user = AdminService.get_one_user(user_id)
    return render_template("admin/user/detail.html", user=user)


@api.route('/user/remove/<user_id>', methods=['GET'])
def user_remove(user_id):
    return jsonify({"retcode": 0, "errors": "", "success": "True"})


@api.route('/article/list', methods=['GET'])
def article_list():
    return render_template("admin/article/list.html")

apps/website/controllers/article_controller.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'

from flask import Blueprint, current_app, request, jsonify

# import json
# from ..mongo import ArticleDB
# from threading import Thread
# import time, datetime
# from ..utils import model2dict
# from ..mredis import RedisClient

api = Blueprint('article_controller', __name__, url_prefix='/article')


@api.route('/', methods=['GET'])
def index():
    return 'article index'

apps/website/controllers/init_controller.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'

from flask import Blueprint, render_template

api = Blueprint('init_controller', __name__, url_prefix='/init')


@api.route('/', methods=['GET'])
def index():
    return render_template("init/index.html")

apps/website/controllers/robot_controller.py
# coding:utf-8
__author__ = 'zhaojm'

from flask import Blueprint, current_app, request, jsonify
import json
from ..mongo import EventDB, ClusterDB, UserDB, QQBindCodeDB
from threading import Thread
import time, datetime
from ..utils import model2dict
from ..mredis import RedisClient

api = Blueprint('robot_controller', __name__, url_prefix='/qq')


@api.route('/', methods=['GET'])
def index():
    return 'robot index'

apps/website/controllers/users_controller.py
# -*- coding:utf-8 -*-
__author__ = 'Van'
from flask import request, Blueprint, current_app, jsonify
from ..utils import model2dict
from ..mongo import UserDB, QQBindCodeDB, ClusterDB
import json

api = Blueprint('users_controller', __name__, url_prefix='')

apps/website/services/views/admin_service.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'

from commons.mongo_db.user.user_db import UserDB


class AdminService(object):
    def __init__(self):
        pass

    @staticmethod
    def check_is_need_init():
        if UserDB.get_admin_user():
            return False
        else:
            return True

    @staticmethod
    def check_is_login():
        return True

apps/website/services/views/article_service.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'


class ArticleService(object):
    def __init__(self):
        pass

apps/website/services/views/home_service.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'


class HomeService(object):
    def __init__(self):
        pass

    pass

apps/website/services/views/index_service.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'


class IndexService(object):
    def __init__(self):
        pass

    pass

apps/website/services/views/init_service.py
# -*- coding:utf-8 -*-
__author__ = 'zhaojm'


class InitService(object):
    def __init__(self):
        pass

apps/website/templates/article/detail.html
{% extends 'article/base.html' %}

{% block title %}detail{% endblock %}

{% block body %}
detail
{% endblock %}

apps/website/templates/article/edit.html
{% extends 'article/base.html' %}

{% block title %}edit{% endblock %}

{% block body %}
edit
{% endblock %}

apps/website/templates/article/list.html
{% extends 'article/base.html' %}

{% block title %}list{% endblock %}

{% block body %}
list
{% endblock %}

apps/website/templates/article/post.html
{% extends 'article/base.html' %}

{% block title %}post{% endblock %}

{% block body %}
post
{% endblock %}

apps/website/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    {% block head %}

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}base{% endblock %}</title>

    <link rel="shorcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">

    {% block head_script %}{% endblock %}

    {% endblock %}

</head>


<body>

{% block body %}
base body
{% endblock %}

</body>
</html>

apps/website/templates/base/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    {% block head %}
    <title>base</title>
    {% endblock %}
</head>
<body>

{% block body %}
base body
{% endblock %}

</body>
</html>

apps/website/templates/home/about.html
{% extends 'home/base.html' %}

{% block title %}about{% endblock %}

{% block main %}
about
{% endblock %}

apps/website/templates/home/admin.html
{% extends 'base/base.html' %}
{% block head %}
<title>admin</title>
{% endblock %}
{% block body %}
admin
{% endblock %}

apps/website/templates/home/article/base.html
{% extends 'home/base.html' %}

{% block title %}article base{% endblock %}




{% block main %}
<div class="container">
    <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
    </div>

    <div class="row">

        {% block sub_main %}
        {% endblock %}

        {% block sidebar %}

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            {#
            <div class="sidebar-module sidebar-module-inset">#}
                {# <h4>About</h4>#}
                {# <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
                    fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>#}
                {#
            </div>
            #}

            <div class="sidebar-module">
                <h4>Categories</h4>
                <ol class="list-unstyled">
                    {% for category in category_list %}
                    <li><a href="{{ url_for('article_controller.article_list_by_category', category=category.title) }}">{{
                        category.title }}</a></li>
                    {% endfor %}
                </ol>
            </div>

            <div class="sidebar-module">
                <h4>Tags</h4>
                <ol class="list-unstyled">
                    {% for tag in tag_list %}
                    <li>
                        <a href="{{ url_for('article_controller.article_list_by_tag', tag=tag.title) }}">{{ tag.title
                            }}</a>
                    </li>
                    {% endfor %}
                </ol>
            </div>

            <div class="sidebar-module">
                <h4>Archives</h4>
                <ol class="list-unstyled">
                    <li><a href="#">March 2014</a></li>
                    <li><a href="#">February 2014</a></li>
                    <li><a href="#">January 2014</a></li>
                    <li><a href="#">December 2013</a></li>
                    <li><a href="#">November 2013</a></li>
                    <li><a href="#">October 2013</a></li>
                    <li><a href="#">September 2013</a></li>
                    <li><a href="#">August 2013</a></li>
                    <li><a href="#">July 2013</a></li>
                    <li><a href="#">June 2013</a></li>
                    <li><a href="#">May 2013</a></li>
                    <li><a href="#">April 2013</a></li>
                </ol>
            </div>
            <div class="sidebar-module">
                <h4>Elsewhere</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
        </div><!-- /.blog-sidebar -->
        {% endblock %}

    </div><!-- /.row -->

</div><!-- /.container -->


{% block foot %}
<div class="blog-footer">
    <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a
            href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</div>
{% endblock %}
{% endblock %}

apps/website/templates/home/article/detail.html
{% extends 'home/article/base.html' %}

{% block title %}detail{% endblock %}

{% block sub_main %}
<div id="article_detail">
    <input id="article_id" value="{{ article._id }}" hidden/>
    <h1 id="title">{{ article.title }}</h1><br/>
    <div>
        author: <span id="author">{{ article.author }}</span><br/>
        category: <span id="category">{{ article.category }}</span><br/>
        tags: <span id="tags">
        {% for tag in tag_list %}
            <span>{{ tag.title }}</span>
        {% endfor %}
        </span><br/>
        create time: <span id="create_time">{{ article.create_time }}</span><br/>
        update time: <span id="update_time">{{ article.update_time }}</span><br/>
    </div>
    <div>
        {{ article.content }}
    </div>
    <div>
        <ul>
            {% for comment in comment_list %}
            <li>{{ comment.title }}</li>
            {% endfor %}
        </ul>
    </div>


</div>
{% endblock %}

apps/website/templates/home/article/index.html
{% extends 'home/article/base.html' %}

{% block title %}index{% endblock %}

{% block sub_main %}
<div class="col-sm-8 blog-main">

    {% for article in article_list %}
    <div class="blog-post">
        <h2 class="blog-post-title">{{ article.title }}</h2>
        <p class="blog-post-meta">{{ article.create_time }} by <a href="#">{{ article.author }}</a></p>

        {{ article.content }}

    </div><!-- /.blog-post -->

    {% endfor %}


    <nav>
        <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
        </ul>
    </nav>

</div><!-- /.blog-main -->
{% endblock %}

apps/website/templates/home/article/list.html
{% extends 'home/article/base.html' %}

{% block title %}list{% endblock %}

{% block sub_main %}
<div class="col-sm-8 blog-main">

    {% for article in article_list %}
    <div class="blog-post">
        <h2 class="blog-post-title">{{ article.title }}</h2>
        <p class="blog-post-meta">{{ article.create_time }} by <a href="#">{{ article.author }}</a></p>

        {{ article.content }}

    </div><!-- /.blog-post -->

    {% endfor %}


    <nav>
        <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
        </ul>
    </nav>

</div><!-- /.blog-main -->
{% endblock %}

apps/website/templates/home/base.html
{% extends 'base.html' %}

{% block head_script %}
<link href="{{ url_for('static', filename = 'app/node_modules/bootstrap/dist/css/bootstrap.min.css') }}"
      rel="stylesheet">
<script type="text/javascript" src="{{ url_for('static', filename = 'app/dist/bundle.js') }}"></script>
{% endblock %}

{% block title %}home{% endblock %}

{% block body %}
{% block menubar %}
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">

            <a class="blog-nav-item active" href="{{ url_for('home_controller.index') }}">Home</a>

            <a class="blog-nav-item" href="{{ url_for('article_controller.index') }}">Article</a>

            <a class="blog-nav-item" href="{{ url_for('home_controller.about') }}">About</a>
            <a class="blog-nav-item" href="{{ url_for('home_controller.contact') }}">Contact</a>

        </nav>
    </div>
</div>


{% endblock %}

{% block main %}
home base main
{% endblock %}

{% block bottom_script %}
<script src="{{ url_for('static', filename = 'app/node_modules/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename = 'app/node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>

{% endblock %}

{% endblock %}

apps/website/templates/home/contact.html
{% extends 'home/base.html' %}

{% block title %}contact{% endblock %}

{% block main %}
contact
{% endblock %}

apps/website/templates/home/home.html
{% extends 'base/base.html' %}

{% block head %}

<title>home</title>

{% endblock %}

{% block body %}

<ul>
    <li><a href="{{ url_for('home_controller.index') }}">Home</a></li>
    {% for category in categories %}
    <li><a href="{{ url_for('article_controller.category', id=category._id) }}">{{ category.title }}</a></li>
    {% endfor %}
    <li><a href="{{ url_for('home_controller.about') }}">About</a></li>
    <li><a href="{{ url_for('home_controller.contact') }}">Contact</a></li>
</ul>

{% endblock %}

apps/website/templates/home/home/base.html
{% extends 'base.html' %}

{% block head_script %}
<script type="text/javascript" src="{{ url_for('static', filename = 'app/dist/bundle.js') }}"></script>
{% endblock %}

{% block title %}home{% endblock %}

{% block body %}

{% block menubar %}
<ul>
    <li><a href="{{ url_for('home_controller.index') }}">Home</a></li>
    <li><a href="{{ url_for('article_controller.article_list_all') }}">Articles</a></li>
    <li><a href="{{ url_for('home_controller.about') }}">About</a></li>
    <li><a href="{{ url_for('home_controller.contact') }}">Contact</a></li>
    <li>Other wait time..</li>
</ul>
{% endblock %}


{% block sidebar %}
home base sidebar
{% endblock %}

{% block main %}
home base main
{% endblock %}

{% endblock %}

apps/website/templates/home/index.html
{% extends 'home/base.html' %}

{% block title %}home{% endblock %}

{% block sidebar %}
{% endblock %}

{% block main %}
<div id="home_main"></div>
{% endblock %}

apps/website/templates/init/index.html
{% extends 'base.html' %}

{% block title %}init{% endblock %}

{% block body %}
init index
{% endblock %}